import CourseHeader from "@/components/CourseHeader";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { useLocalCourseProgress } from "@/hooks/useLocalCourseProgress";
import { courseModules, findLesson } from "@shared/course";
import { ArrowRight, Award, BookOpenCheck, CheckCircle2, Circle, Compass, Leaf, RotateCcw, StickyNote } from "lucide-react";
import { useLocation } from "wouter";

export default function Dashboard() {
  const [, setLocation] = useLocation();
  const { completedSet, completedCount, totalLessons, nextLessonId, resumeLessonId, resetProgress, notesCount } = useLocalCourseProgress();
  const percent = Math.round((completedCount / totalLessons) * 100);
  const resumeLesson = findLesson(resumeLessonId);
  const nextLesson = findLesson(nextLessonId);

  return <div className="hris-app min-h-screen bg-[#fbfbf8] text-[#102a43]"><CourseHeader /><main className="container py-9 sm:py-12"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="section-kicker">Your open learning desk</p><h1 className="font-display mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Learn at your own pace.</h1><p className="mt-3 max-w-2xl text-lg leading-7 text-slate-600">No account is required. Choose a lesson, practice the work, and let this browser remember where you are.</p></div><div className="w-full rounded-2xl border border-[#e5e1d7] bg-white px-5 py-4 sm:max-w-sm"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9a6b1d]">Course progress</p><div className="mt-1 flex items-end gap-2"><span className="font-display text-3xl font-semibold tracking-tight">{percent}%</span><span className="mb-1 text-sm text-slate-500">{completedCount} of {totalLessons} lessons</span></div></div><span className="rounded-full bg-[#fff4d8] px-2.5 py-1 text-xs font-bold text-[#9a6b1d]">Overall</span></div><Progress value={percent} aria-label={`Overall course completion: ${percent}%`} className="mt-4 h-3 bg-[#ece9e1] [&>div]:bg-[#c28b24]" /></div></div>

    <section className="mt-9 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><article className="relative overflow-hidden rounded-[1.8rem] bg-[#102a43] p-7 text-white shadow-[0_22px_45px_rgba(16,42,67,.16)] sm:p-9"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-[#f3c969]/20 blur-2xl" /><div className="relative"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#f3c969]"><Compass className="h-4 w-4" /> Continue learning</div><h2 className="font-display mt-4 max-w-xl text-3xl font-semibold tracking-[-.035em]">{resumeLesson?.title ?? "Start your HR career diagnostic"}</h2><p className="mt-3 max-w-xl leading-7 text-[#c5d3dd]">{resumeLesson?.summary ?? "Begin with your evidence-led baseline before moving into the full curriculum."}</p><Button className="mt-7 rounded-full bg-[#f3c969] px-5 font-bold text-[#102a43] hover:bg-[#f9d77e]" onClick={() => setLocation(`/learn/${resumeLesson?.id ?? nextLesson?.id}`)}>Open lesson <ArrowRight className="ml-2 h-4 w-4" /></Button></div></article><article className="rounded-[1.8rem] border border-[#e5e1d7] bg-white p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#fff4d8] text-[#a46d16]"><Leaf className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9a6b1d]">Private by design</p><h2 className="font-display text-xl font-semibold">Saved only on this device</h2></div></div><p className="mt-5 text-sm leading-6 text-slate-600">Completion, resume position, and {notesCount ? `${notesCount} lesson note${notesCount === 1 ? "" : "s"}` : "your lesson notes"} use local browser storage. No email address, password, or profile is collected.</p><div className="mt-4 flex items-center gap-2 text-sm font-semibold text-[#527080]"><StickyNote className="h-4 w-4 text-[#b77b19]" />{notesCount ? `${notesCount} saved lesson note${notesCount === 1 ? "" : "s"}` : "Add notes in any lesson"}</div><Button variant="outline" className="mt-5 w-full rounded-full border-[#d9d6cd] bg-white text-[#527080] hover:border-red-200 hover:bg-red-50 hover:text-red-700" onClick={resetProgress}><RotateCcw className="mr-2 h-4 w-4" /> Reset local progress</Button></article></section>

    <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="section-kicker">Your pathway</p><h2 className="font-display mt-2 text-3xl font-semibold tracking-[-.035em]">Curriculum progress</h2></div><span className="hidden text-sm text-slate-500 sm:block">Every module ends with suggestions and interview practice.</span></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courseModules.map((module) => { const done = module.lessons.filter((item) => completedSet.has(item.id)).length; const modulePercent = Math.round((done / module.lessons.length) * 100); return <article key={module.id} className="rounded-2xl border border-[#e5e1d7] bg-white p-5 transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_12px_25px_rgba(30,47,64,.07)]"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9a6b1d]">{module.level}</p><h3 className="mt-2 text-lg font-semibold text-[#102a43]">{module.title}</h3></div><span className="rounded-full bg-[#edf3f5] px-2.5 py-1 text-xs font-bold text-[#527080]">{done}/{module.lessons.length}</span></div><Progress value={modulePercent} className="mt-5 h-1.5 bg-[#e8edf0]" /><div className="mt-4 space-y-2">{module.lessons.map((item) => <button key={item.id} onClick={() => setLocation(`/learn/${item.id}`)} className="group flex w-full items-center gap-2 text-left text-sm text-slate-600 transition hover:text-[#102a43]"><span className="text-[#b77b19]">{completedSet.has(item.id) ? <CheckCircle2 className="h-4 w-4" /> : <Circle className="h-4 w-4" />}</span><span className="flex-1 truncate">{item.title}</span><ArrowRight className="h-3.5 w-3.5 opacity-0 transition group-hover:translate-x-0.5 group-hover:opacity-100" /></button>)}</div><div className="mt-5 flex items-center gap-2 border-t border-[#eeeae2] pt-4 text-xs font-semibold text-[#527080]"><BookOpenCheck className="h-4 w-4 text-[#b77b19]" /> Suggestions & interview challenge</div></article>})}</div></section>
  </main></div>;
}
